<a href="https://colab.research.google.com/github/mattscolieri/BME3053C-Fall-2025/blob/main/study-guides/midterm-study-guide_10.26.25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BME3053C Midterm Study Guide

This Jupyter Notebook provides practice problems covering concepts included in the midterm.

- Conditionals (if/elif/else)
- Boolean logic
- Type conversion
- Loops (for/while)
- List slicing
- References and mutability
- Functions and Variable scope
- NumPy array operations (basic arithmetic, broadcasting)
- Pandas Conditionals
- Indexing and Iteration in Pandas
- Matrix Transformations

Try each code snippet, predict the output, and then run the code to confirm your understanding.

### Original Lesson Link: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/uf-bme/BME3053C-Fall-2025/blob/main/study-guides/midterm-study-guide.ipynb)


## Tips to Succeed

- Don't rush through the problems! Pay close attention to the syntax in each code cell (especially in print statements).
- Try tweaking the code cells in this notebook to see how changes affect the output. Write down your predictions and the modified code on paper before running it.
- Review the output and compare it with your predictions to reinforce your understanding.


## Conditionals and Boolean Logic

- Conditionals allow you to execute different blocks of code based on certain conditions.

#### Multiple Conditionals in a Single Statement

- You can combine multiple conditions in a single `if`, `elif`, or `else` statement
- Boolean logic helps in combining multiple conditions using logical operators like `and`, `or`, and `not`.
- When using `and`, the condition will only be true if both conditions are true.
- When using `or`, the condition will be true if at least one of the conditions is true.
- Parentheses will help ensure the condition is evaluated in the order you want.

#### Practice

Predict the prints, then run the cells below to check.


In [ ]:
x = 6
y = 3

if x > 5 and y < 3:
    print("Case 1")
elif x == 6 or y == 4:
    print("Case 2")
else:
    print("Case 3")
print("Done")

Case 2
Done


In [ ]:
a = 10
b = 9
c = 7

if (a > b) and (b < c):
    print("Condition 1")
elif (b > a) or (b < c):
    print("Condition 2")
else:
    print("Condition 3")
print("Done")

Condition 3
Done


## Type Conversion

- Type conversion is the process of converting one data type to another.
- This is useful when you need to convert data from one type to another.
- The `int()`, `str()`, and `float()` functions are commonly used for type conversion.

**On the test, you could just write int or float. You wouldn't need to write <class 'int'> or <class 'float'>**

**Task:** Understand how to convert between different data types using `int()`, `str()`, and `float()` functions.


In [ ]:
num_str = "123"

print("num_str")


num_int = int(num_str)
print(num_int, type(num_int))



float_num = 12.34
int_num = int(float_num)
print(int_num, type(int_num))

bool_val = True
str_bool = str(bool_val)
print(str_bool, type(str_bool))


num_str
123 <class 'int'>
12 <class 'int'>
True <class 'str'>


## For Loops

- A for loop is used to iterate over a sequence (such as a list, tuple, dictionary, set, or string).
- The range() function is commonly used with for loops to generate a sequence of numbers.
- The `range()` function can take 1, 2, or 3 arguments:
  - `range(stop)`: generates numbers from 0 to stop-1
  - `range(start, stop)`: generates numbers from start to stop-1
  - `range(start, stop, step)`: generates numbers from start to stop-1, incrementing by step

### Prompt

```python
total_sum = 0
for i in range(3, 8):  # 3, 4, 5, 6, 7
    total_sum += i
print(total_sum)
```

**Task:** Predict the final value of `total_sum`.


In [ ]:
total_sum = 0
for i in range(3, 6,2):
    print('i=',i,'total_sum=',total_sum)
    total_sum += i

print(total_sum)

i= 3 total_sum= 0
i= 5 total_sum= 3
8


### Continue and Break Statements

- **Break Statement in Python:**

  - Immediately exits the loop when executed.
  - Useful when a certain condition is met and no further iterations are needed.
  - Example:
    ```python
    for num in range(10):
        if num == 5:
            break  # Exit the loop
        print(num)
    ```

- **Continue Statement in Python:**
  - Skips the rest of the code in the current loop iteration.
  - Proceeds directly to the next iteration of the loop.
  - Example:
    ```python
    for num in range(10):
        if num % 2 == 0:
            continue  # Skip even numbers
        print(num)
    ```


In [ ]:
for i in range(2,10,2):
  if i < 6:
    continue
  print('i=',i)
print('final',i)

i= 6
i= 8
final 8


In [ ]:
total_sum = 0
for i in range(1, 7,3):
    if i == 4:
      continue
    if i > 5:
      break
    total_sum += i
    print(i,total_sum)

print('final',i,total_sum)


1 1
final 4 1


## While Loops

- A while loop is used to execute a block of code repeatedly as long as a condition is true.
- The condition is evaluated before each iteration of the loop.

**Task:** Observe how the loop increments `count` and prints when `count == 2`.


In [ ]:
count = 0
count2 = 0

while count < 5:
    count2+=1
    if count == 2:
        print("count2=",count2)
        count2+=1
    count += 1

print("Final count:", count)
print("Final count2:",count2)

count2= 3
Final count: 5
Final count2: 6


## List Slicing

- List slicing allows you to extract a portion of a list.
- The syntax is `list[start:stop:step]`.
- The start index is **inclusive**, the stop index is **exclusive**
- Negative indices can be used to slice from the end of the list.
- The step can be negative to reverse the order of the slice.


In [ ]:
nums = [10, 20, 30, 40, 50, 60]

In [ ]:
print("nums[2:] =>", nums[2:])

nums[2:] => [30, 40, 50, 60]


In [ ]:
print("nums[:3] =>", nums[:3])

nums[:3] => [10, 20, 30]


In [ ]:
print("nums[1:5:2] =>", nums[1:5:2])

nums[1:5:2] => [20, 40]


In [ ]:
print("nums[1:4] =>", nums[1:4])

nums[1:4] => [20, 30, 40]


In [ ]:
print("nums[-3:-1:1] =>", nums[-3:-1:1])

nums[-3:-1:1] => [40, 50]


In [ ]:
print("nums[-3:1:-1] =>", nums[-3:1:-1])

nums[-3:1:-1] => [40, 30]


## References & Mutability

- Lists are mutable, meaning their contents can be changed after they are created.
- When a list is assigned to a new variable, the new variable references the same list.

**Task:** Understand how inserting into `another_ref` also affects `a_list` because both point to the same list.


In [1]:
a_list = [5, 6]
another_ref = a_list
another_ref.append(10)

print("a_list =", a_list)
print("another_ref =", another_ref)

a_list = [5, 6, 10]
another_ref = [5, 6, 10]


In [2]:
import copy
a_list = [5, 6]
another_ref = copy.deepcopy(a_list)
another_ref.append(10)

print("a_list =", a_list)
print("another_ref =", another_ref)

a_list = [5, 6]
another_ref = [5, 6, 10]


## Variable Scope

Variable scope refers to the context in which a variable is defined and accessible. In Python, there are two main types of variable scope:

1. **Global Scope**: Variables defined outside of any function or block, accessible throughout the entire script.
2. **Local Scope**: Variables defined within a function or block, accessible only within that function or block.

Understanding variable scope is crucial for avoiding naming conflicts and ensuring that variables are used correctly within their intended context.

**Task:** Notice how `my_var` inside the function is not the same as the **global** `my_var`.


In [3]:
my_var = 100
def multiply_by_two(x):
    my_var = x * 2
    return my_var

result = multiply_by_two(5)
print("my_var =", my_var)
print("result =", result)

my_var = 100
result = 10


## Function Parameters and Return Values

- When working with functions, it's important to understand how return values and variable scope work.
- In the example below, the function `add_two_numbers` is supposed to return the sum of two numbers, but it currently returns x.

**Task:** Evaluate the importance of return values in the function `add_two_numbers`.


In [12]:

def add_two_numbers(x,y=0):
    local_var = x + y
    return x + y


In [8]:
var1 = 7

var2 = add_two_numbers(5)

var3 = var1+var2
print(var3)

12


In [13]:
var1 = 7

var2 = add_two_numbers(3,4)

var3 = var1+var2
print(var3)

14


## NumPy: Basic Arithmetic & Broadcasting

- NumPy arrays support element-wise arithmetic operations like addition, subtraction, multiplication, and division.
- You can perform operations between arrays and scalars, or between arrays of compatible shapes.
- The `@` operator is used for matrix multiplication, while `*` performs element-wise multiplication.
- Broadcasting is a feature of NumPy that allows for element-wise operations between arrays of different shapes.

**Task:** Practice element-wise operations.\*\*


In [14]:
import numpy as np
x_mat = np.array([[4, 5, 6], [1, 2, 3],[7, 8, 9]])
y_mat = np.array([[1, 2, 3], [4, 5, 6],[4, 6, 8]])
print('x_mat:')
print(x_mat)
print()
print('y_mat:')
print(y_mat)

x_mat:
[[4 5 6]
 [1 2 3]
 [7 8 9]]

y_mat:
[[1 2 3]
 [4 5 6]
 [4 6 8]]


In [15]:
print(x_mat * 2)

[[ 8 10 12]
 [ 2  4  6]
 [14 16 18]]


In [16]:
print(x_mat + y_mat)

[[ 5  7  9]
 [ 5  7  9]
 [11 14 17]]


In [17]:
print(x_mat * y_mat)

[[ 4 10 18]
 [ 4 10 18]
 [28 48 72]]


In [18]:
print(y_mat * x_mat)

[[ 4 10 18]
 [ 4 10 18]
 [28 48 72]]


In [19]:
print(x_mat @ y_mat)

[[ 48  69  90]
 [ 21  30  39]
 [ 75 108 141]]


In [20]:
print(y_mat @ x_mat)

[[ 27  33  39]
 [ 63  78  93]
 [ 78  96 114]]


# Filtering data with conditionals in Pandas

Pandas makes it easy to select, analyze, and process subsets of your data based on some condition `C`. This is accomplished with easily understandable syntax: `df[C]` will return a subset of DataFrame `df` that **matches** the condition `C` listed inside brackets `[]`.

- we can create filtering criteria using familiar mathematical operators that were used in Python conditionals.

**You will only need to write the indices of the rows that would be included in each condition**


In [22]:
import pandas as pd
import numpy as np

# Create a new dataframe with 5 rows and 3 columns
df = pd.DataFrame({
    'Species': ['cat', 'dog', 'bird', 'cat', 'dog'],
    'Age': [13,11,18,18,8],
    'Weight': [13.3,32.4,2.4,19.3, 64.1],
})


In [23]:
df

Species  Age  Weight
0     cat   13    13.3
1     dog   11    32.4
2    bird   18     2.4
3     cat   18    19.3
4     dog    8    64.1

In [24]:
print(df[df['Age'] > 8])

  Species  Age  Weight
0     cat   13    13.3
1     dog   11    32.4
2    bird   18     2.4
3     cat   18    19.3


In [25]:
print(df[(df['Age'] > 8) & (df['Weight'] > 20)])

  Species  Age  Weight
1     dog   11    32.4


In [26]:
print(df[(df['Species'] == 'cat') & (df['Species'] == 'dog')])

Empty DataFrame
Columns: [Species, Age, Weight]
Index: []


In [28]:
print(df[(df['Species'] == 'cat') | (df['Species'] == 'dog')])

  Species  Age  Weight
0     cat   13    13.3
1     dog   11    32.4
3     cat   18    19.3
4     dog    8    64.1


## Indexing and Iteration

### Accessing Data in DataFrames

- Use `.iloc[]` for integer position-based indexing (e.g., df.iloc[0, 1] for first row, second column)
- Use `.loc[]` for label-based indexing (e.g., df.loc['row_label', 'column_name'])

- Example:
  - df.iloc[0, 1] gets value in first row, second column regardless of labels
  - df.loc['A', 'price'] gets value where index='A' and column='price'


In [ ]:
df

In [ ]:
print("First row, second column using iloc:")
print(df.iloc[0, 1])

In [ ]:
print("Accessing row 0, column 'B' using loc:")
print(df.loc[0, 'Weight'])

In [ ]:
print(df.iloc[0:4:2,2])

## Transformation Matrices in Homogeneous Coordinates

Transformation matrices allow us to perform geometric operations (rotation, scaling, translation) on 2D shapes using matrix multiplication. In homogeneous coordinates, we represent 2D points as 3D vectors [x, y, 1], which enables us to express all transformations—including translation—as matrix multiplications.

**Important Notes:**

- Matrix multiplication order matters! Transformations are applied **right to left**
- To rotate around a point (cx, cy) other than the origin: translate to origin → rotate → translate back
- Multiple transformations can be combined into a single matrix by multiplying them together


<center><img  src="https://github.com/uf-bme/bme3053c/raw/main/files/2D_affine_transformation_matrix.svg" alt='Matrix Transformations'/></center>


### Example: Rotation + Scaling + Translation

We can also combine rotation, scaling, and translation in one step by multiplying their respective matrices together:

$$Combined=T⋅S⋅R(θ)$$

This order applies the rotation first, then scaling, and finally translation.


In [ ]:
import numpy as np

import matplotlib.pyplot as plt

# Enable inline plotting
%matplotlib inline

def generate_star(center=(0, 0), num_points=5, outer_radius=1, inner_radius=0.5,homogeneous=False):
    '''
    This function generates the coordinates of a star shape based on the specified number of points,
    outer radius, inner radius, and center coordinates. The star is created by alternating between the
    outer and inner radii at calculated angles, resulting in a visually appealing star pattern.
    '''
    angles = np.linspace(np.pi/2, 5*np.pi/2, num_points*2, endpoint=False)
    radii = np.array([outer_radius, inner_radius] * num_points)
    x = radii * np.cos(angles) + center[0]
    y = radii * np.sin(angles) + center[1]
    return np.column_stack((x, y)) if not homogeneous else np.column_stack((x, y, np.ones(num_points*2)))

def plot_star(ax, star, title,global_view):
    ax.plot(star[:, 0], star[:, 1], 'b-')
    ax.plot([star[-1, 0], star[0, 0]], [star[-1, 1], star[0, 1]], 'b-')  # Connect last to first
    ax.set_title(title)
    ax.axis('equal')
    if global_view:
      ax.set_xlim(-10,10)
      ax.set_ylim(-10,10)
      ax.axhline(0, color='black')
      ax.axvline(0, color='black')

    ax.grid(True)  # Add grid

    star_center = np.mean(star, axis=0)
    arrow_start = star_center

    vector_to_point = star[0] - star_center
    direction = vector_to_point/np.linalg.norm(vector_to_point)  # Normalize the direction vector
    arrow_length = np.linalg.norm(vector_to_point)/2
    arrow_end = star_center + (arrow_length) * direction
    headwidth=6 if global_view else 8
    width = 1 if global_view else 2
    ###########################################
    ax.annotate('', xy=arrow_end, xytext=arrow_start,
                arrowprops=dict(facecolor='green', shrink=0.05, width=width, headwidth=headwidth))

def plot_stars(stars,global_view=False):
    if len(stars) == 1 or not isinstance(stars, list):
        print("There must be a list of multiple stars to plot")
        return
    num_stars = len(stars)
    fig, axs = plt.subplots(1, num_stars, figsize=(10, 5))
    for i, star in enumerate(stars):
        plot_star(axs[i], star[:,:2], f'Star {i+1}',global_view)

def rotate(angle_degrees):
    angle_radians = np.radians(angle_degrees)
    cos_theta = np.cos(angle_radians)
    sin_theta = np.sin(angle_radians)
    return np.array([
        [cos_theta, -sin_theta,0],
        [sin_theta, cos_theta,0],
        [0,0,1],
    ])


def scale(sx,sy):
    return np.array([
        [sx, 0,0],
        [0, sy,0],
        [0,0,1],
    ])

def translate(tx, ty):
    return np.array([
        [1, 0, tx],
        [0, 1, ty],
        [0, 0, 1]
    ])

In [ ]:
star=generate_star(homogeneous=True)

combined_transform =  translate(1,2) @scale(2,2)@ rotate(45)

transformed_star = (combined_transform @ star.T).T

plot_stars([star,transformed_star],global_view=True)

In [ ]:
star=generate_star(center=(1,1),homogeneous=True)

combined_transform =  translate(1,2) @ rotate(-45)@translate(-1,-1)

transformed_star = (combined_transform @ star.T).T

plot_stars([star,transformed_star],global_view=True)

In [ ]:
star=generate_star(center=(-4,-4),homogeneous=True)

combined_transform = rotate(-180)

transformed_star = (combined_transform @ star.T).T

plot_stars([star,transformed_star],global_view=True)

## **Good luck!**
